# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutRobot(object):
    def setupUi(self, AboutRobot):
        AboutRobot.setObjectName("AboutRobot")
        AboutRobot.resize(929, 668)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AboutRobot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(AboutRobot)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)

        self.retranslateUi(AboutRobot)
        QtCore.QMetaObject.connectSlotsByName(AboutRobot)

    def retranslateUi(self, AboutRobot):
        _translate = QtCore.QCoreApplication.translate
        AboutRobot.setWindowTitle(_translate("AboutRobot", "Form"))
        self.textBrowser.setHtml(_translate("AboutRobot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">这是一个</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">严肃</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\">的计划，为了测试我们是否有合作能力而制定，但是核心主要还是实现我们</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-style:italic; color:#24292e;\">共同爱好与目标</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\">，难得的聚集到了各个领域都很强的人，不尝试去实现人生目标实在可惜。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">在此之前的很长一段时间，有想法但是并未有确切去实现，因此Robot只是一种乌托邦式的存在，所以现在制定一个计划，希望我们大家能一起实现目标，并且希望在未来能有更好的发展。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">Q:为什么这个计划是一年？</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">A:因为我们现阶段是大三，实话说有些晚了，但是也不晚</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\">，因为大三了大家学到的知识相对也比较丰富和成熟，其实也是一个非常适合的阶段。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">但是有不足的就是，大家的可自由支配时间变少了，都有各自要忙的事情和其他的目标，所以设定了一年的时间，想到的是，大家能有比较多的缓冲时间，在Robot上的时间分配上也会更充足一些。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">这个计划从开始到结束都要准时执行，由2020.10.12到2021.10.12.</span></p>\n"
"<p style=\" margin-top:24px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:1.25%; background-color:#ffffff;\"><a name=\"user-content-目前分为三个阶段\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">目</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">前分为三个阶段</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">前期(2020.10.18-2020.12.18)</span></li>\n"
"<li style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\" style=\" margin-top:3px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">中期(2020.12.19-2021.04.19)</span></li>\n"
"<li style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\" style=\" margin-top:3px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">后期(2021.04.20-?)。</span></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">而在这几个阶段中，等我们配合逐渐成雏形以后，大家各自成熟以后，就可以慢慢开始一步步</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">吸纳新人。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">而且在前期大家都适应以后，就可以定期开展交流会,预计是前期的中旬或者前期的后旬。</span></p>\n"
"<p style=\" margin-top:24px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:1.25%; background-color:#ffffff;\"><a name=\"user-content-前期\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">前</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">期</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">每个人定时每个星期做一个各自负责领域的小项目，这个小项目需要自己去找，然后建一个私有仓库，用markdown写下README，上传到github上面</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">可以互相观看互相学习，这样也可以让彼此了解一下对方所作的东西。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">可以组队合作完成,过完这个阶段就要初步确定自己的定位！在一个项目中的定位！知道做出一个产品所需要确定的定位。</span></p>\n"
"<p style=\" margin-top:24px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:1.25%; background-color:#ffffff;\"><a name=\"user-content-中期\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">中</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">期</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">这个阶段，我们会寻找一些开源的中型项目来练手，从最简单的入手，再循循渐进，慢慢加大难度，直到这期间磨练出我们合作的能力。在这个时候可以建立公共仓库，可以自行组队，做团队型项目。</span></p>\n"
"<p style=\" margin-top:24px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:1.25%; background-color:#ffffff;\"><a name=\"user-content-后期\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">后</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">期</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">这个阶段，我们就开始着手做Robot，这个是最核心和统一的目标，因为做Robot需要钱，所以这个阶段也会去找外包的项目等一些能赚钱的项目来做，赚到的钱作为我们的资金。</span></p>\n"
"<p style=\" margin-top:24px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:1.25%; background-color:#ffffff;\"><a name=\"user-content-最后\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">最</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:large; font-weight:600; color:#24292e;\">后</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">实话实说，这个计划</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; color:#24292e;\">不单单是为了梦想</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e;\">，但是是由梦想起步的，等到我们有一定的能力，我们可以将这个小团体作为以后的发展，在期间，我们会收集一些比赛和项目来参加。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">一方面，锻炼我们的合作能力和项目经验，一方面我们可以丰富我们的简历，而且也可以赚到一小部分资金，作为我们的发展，其中发展资金我们可以拿来购买教程，购买开发板。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; font-weight:600; font-style:italic; color:#24292e;\">希望我们都能保持初心不变，一直朝着相同的目标努力，麻雀虽小但五脏俱全，谁说的定，我们以后也是一个大团体呢，共勉！</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji\'; font-size:16px; color:#24292e; background-color:#ffffff;\">—— ifdcn</span></p></body></html>"))

