# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portInitGroupLayout = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.portInitGroupLayout.setFont(font)
        self.portInitGroupLayout.setObjectName("portInitGroupLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.portInitGroupLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comxLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comxLabel.setFont(font)
        self.comxLabel.setObjectName("comxLabel")
        self.verticalLayout.addWidget(self.comxLabel)
        self.comxCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.comxCombo.setObjectName("comxCombo")
        self.verticalLayout.addWidget(self.comxCombo)
        self.baudLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.baudLabel.setFont(font)
        self.baudLabel.setObjectName("baudLabel")
        self.verticalLayout.addWidget(self.baudLabel)
        self.baudCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.baudCombo.setObjectName("baudCombo")
        self.verticalLayout.addWidget(self.baudCombo)
        self.bytesizeLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.bytesizeLabel.setFont(font)
        self.bytesizeLabel.setObjectName("bytesizeLabel")
        self.verticalLayout.addWidget(self.bytesizeLabel)
        self.bytesizeCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.bytesizeCombo.setObjectName("bytesizeCombo")
        self.verticalLayout.addWidget(self.bytesizeCombo)
        self.prrityLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.prrityLabel.setFont(font)
        self.prrityLabel.setObjectName("prrityLabel")
        self.verticalLayout.addWidget(self.prrityLabel)
        self.parityCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.parityCombo.setObjectName("parityCombo")
        self.verticalLayout.addWidget(self.parityCombo)
        self.stopbitLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.stopbitLabel.setFont(font)
        self.stopbitLabel.setObjectName("stopbitLabel")
        self.verticalLayout.addWidget(self.stopbitLabel)
        self.stopbitsCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.stopbitsCombo.setObjectName("stopbitsCombo")
        self.verticalLayout.addWidget(self.stopbitsCombo)
        self.openBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.openBtn.setFont(font)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout.addWidget(self.openBtn)
        self.closebtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.closebtn.setFont(font)
        self.closebtn.setObjectName("closebtn")
        self.verticalLayout.addWidget(self.closebtn)
        self.checkBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.verticalLayout.addWidget(self.checkBtn)
        self.aboutBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.aboutBtn.setFont(font)
        self.aboutBtn.setObjectName("aboutBtn")
        self.verticalLayout.addWidget(self.aboutBtn)
        self.horizontalLayout.addWidget(self.portInitGroupLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 1021, 681))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_11.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_11.addWidget(self.graphicsView_2)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_11.addWidget(self.graphicsView_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statisticGroupLayout = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.statisticGroupLayout.setFont(font)
        self.statisticGroupLayout.setObjectName("statisticGroupLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.statisticGroupLayout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acceptedtext = QtWidgets.QLabel(self.statisticGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.acceptedtext.setFont(font)
        self.acceptedtext.setObjectName("acceptedtext")
        self.horizontalLayout_3.addWidget(self.acceptedtext)
        self.lcdNumber = QtWidgets.QLCDNumber(self.statisticGroupLayout)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendedtext = QtWidgets.QLabel(self.statisticGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sendedtext.setFont(font)
        self.sendedtext.setObjectName("sendedtext")
        self.horizontalLayout_4.addWidget(self.sendedtext)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.statisticGroupLayout)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_4.addWidget(self.lcdNumber_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.statisticGroupLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.acceptedGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.acceptedGroupBox.setFont(font)
        self.acceptedGroupBox.setObjectName("acceptedGroupBox")
        self.textEdit = QtWidgets.QTextEdit(self.acceptedGroupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 731, 261))
        self.textEdit.setObjectName("textEdit")
        self.sendedGroupBox = QtWidgets.QGroupBox(self.acceptedGroupBox)
        self.sendedGroupBox.setGeometry(QtCore.QRect(0, 290, 751, 381))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.sendedGroupBox.setFont(font)
        self.sendedGroupBox.setObjectName("sendedGroupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.sendedGroupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 731, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_10.addWidget(self.textEdit_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout_5.setStretch(0, 4)
        self.horizontalLayout_5.setStretch(1, 5)
        self.horizontalLayout_5.setStretch(2, 4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.acceptedGroupBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.portInitGroupLayout.setTitle(_translate("MainWindow", "PORT-INIT"))
        self.comxLabel.setText(_translate("MainWindow", "COMX:"))
        self.baudLabel.setText(_translate("MainWindow", "BAUD"))
        self.bytesizeLabel.setText(_translate("MainWindow", "BYTESIZE"))
        self.prrityLabel.setText(_translate("MainWindow", "PARITY"))
        self.stopbitLabel.setText(_translate("MainWindow", "STOPBITS"))
        self.openBtn.setText(_translate("MainWindow", "OPEN"))
        self.closebtn.setText(_translate("MainWindow", "CLOSE"))
        self.checkBtn.setText(_translate("MainWindow", "CHECK"))
        self.aboutBtn.setText(_translate("MainWindow", "ABOUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.statisticGroupLayout.setTitle(_translate("MainWindow", "statistics"))
        self.acceptedtext.setText(_translate("MainWindow", "已收到的爱心❤总数 -❤>"))
        self.sendedtext.setText(_translate("MainWindow", "已发送的爱心❤总数 -❤>"))
        self.acceptedGroupBox.setTitle(_translate("MainWindow", "接收❤区"))
        self.sendedGroupBox.setTitle(_translate("MainWindow", "发送❤区"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label.setText(_translate("MainWindow", "ms/次"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "发射和接收爱心射线(づ￣3￣)づ╭❤～"))

