# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portInitGroupLayout = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.portInitGroupLayout.setFont(font)
        self.portInitGroupLayout.setObjectName("portInitGroupLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.portInitGroupLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comxLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comxLabel.setFont(font)
        self.comxLabel.setObjectName("comxLabel")
        self.verticalLayout.addWidget(self.comxLabel)
        self.comxCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.comxCombo.setObjectName("comxCombo")
        self.verticalLayout.addWidget(self.comxCombo)
        self.baudLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.baudLabel.setFont(font)
        self.baudLabel.setObjectName("baudLabel")
        self.verticalLayout.addWidget(self.baudLabel)
        self.baudCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.baudCombo.setObjectName("baudCombo")
        self.verticalLayout.addWidget(self.baudCombo)
        self.comxTimeout = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comxTimeout.setFont(font)
        self.comxTimeout.setObjectName("comxTimeout")
        self.verticalLayout.addWidget(self.comxTimeout)
        self.timeoutSpinBox = QtWidgets.QSpinBox(self.portInitGroupLayout)
        self.timeoutSpinBox.setObjectName("timeoutSpinBox")
        self.verticalLayout.addWidget(self.timeoutSpinBox)
        self.bytesizeLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.bytesizeLabel.setFont(font)
        self.bytesizeLabel.setObjectName("bytesizeLabel")
        self.verticalLayout.addWidget(self.bytesizeLabel)
        self.bytesizeCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.bytesizeCombo.setObjectName("bytesizeCombo")
        self.verticalLayout.addWidget(self.bytesizeCombo)
        self.prrityLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.prrityLabel.setFont(font)
        self.prrityLabel.setObjectName("prrityLabel")
        self.verticalLayout.addWidget(self.prrityLabel)
        self.parityCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.parityCombo.setObjectName("parityCombo")
        self.verticalLayout.addWidget(self.parityCombo)
        self.stopbitLabel = QtWidgets.QLabel(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.stopbitLabel.setFont(font)
        self.stopbitLabel.setObjectName("stopbitLabel")
        self.verticalLayout.addWidget(self.stopbitLabel)
        self.stopbitsCombo = QtWidgets.QComboBox(self.portInitGroupLayout)
        self.stopbitsCombo.setObjectName("stopbitsCombo")
        self.verticalLayout.addWidget(self.stopbitsCombo)
        self.openBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.openBtn.setFont(font)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout.addWidget(self.openBtn)
        self.closebtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.closebtn.setFont(font)
        self.closebtn.setObjectName("closebtn")
        self.verticalLayout.addWidget(self.closebtn)
        self.checkBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.verticalLayout.addWidget(self.checkBtn)
        self.aboutBtn = QtWidgets.QPushButton(self.portInitGroupLayout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.aboutBtn.setFont(font)
        self.aboutBtn.setObjectName("aboutBtn")
        self.verticalLayout.addWidget(self.aboutBtn)
        self.horizontalLayout.addWidget(self.portInitGroupLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1011, 681))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statisticGroupLayout = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.statisticGroupLayout.setFont(font)
        self.statisticGroupLayout.setObjectName("statisticGroupLayout")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.statisticGroupLayout)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 240, 25))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendedtext = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sendedtext.setFont(font)
        self.sendedtext.setObjectName("sendedtext")
        self.horizontalLayout_4.addWidget(self.sendedtext)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_3)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_4.addWidget(self.lcdNumber_2)
        self.debuggroupBox = QtWidgets.QGroupBox(self.statisticGroupLayout)
        self.debuggroupBox.setGeometry(QtCore.QRect(0, 90, 241, 571))
        self.debuggroupBox.setObjectName("debuggroupBox")
        self.debugtextBrowser = QtWidgets.QTextBrowser(self.debuggroupBox)
        self.debugtextBrowser.setGeometry(QtCore.QRect(10, 30, 221, 501))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.debugtextBrowser.setFont(font)
        self.debugtextBrowser.setObjectName("debugtextBrowser")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.statisticGroupLayout)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 28, 240, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acceptedtext = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.acceptedtext.setFont(font)
        self.acceptedtext.setObjectName("acceptedtext")
        self.horizontalLayout_3.addWidget(self.acceptedtext)
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        self.horizontalLayout_2.addWidget(self.statisticGroupLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.acceptedGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.acceptedGroupBox.setFont(font)
        self.acceptedGroupBox.setObjectName("acceptedGroupBox")
        self.textEdit = QtWidgets.QTextEdit(self.acceptedGroupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 711, 281))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.acceptedGroupBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.sendedGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.sendedGroupBox.setFont(font)
        self.sendedGroupBox.setObjectName("sendedGroupBox")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.sendedGroupBox)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(16, 36, 721, 281))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sendedRegion = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        self.sendedRegion.setObjectName("sendedRegion")
        self.verticalLayout_3.addWidget(self.sendedRegion)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.autoCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.autoCheckBox.setObjectName("autoCheckBox")
        self.horizontalLayout_11.addWidget(self.autoCheckBox)
        self.sendLineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.sendLineEdit_4.setObjectName("sendLineEdit_4")
        self.horizontalLayout_11.addWidget(self.sendLineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.sendBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_11.addWidget(self.sendBtn)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 5)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.setStretch(1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.sendedGroupBox)
        self.lineEdit.setGeometry(QtCore.QRect(12, 403, 184, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.sendedGroupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.setStretch(0, 1)
        self.openPortProgressBar = QtWidgets.QProgressBar(self.tab_2)
        self.openPortProgressBar.setGeometry(QtCore.QRect(0, 680, 1011, 51))
        self.openPortProgressBar.setProperty("value", 24)
        self.openPortProgressBar.setObjectName("openPortProgressBar")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 1021, 681))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_11.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_11.addWidget(self.graphicsView_2)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_11.addWidget(self.graphicsView_3)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.portInitGroupLayout.setTitle(_translate("MainWindow", "CC-PORT-INIT"))
        self.comxLabel.setText(_translate("MainWindow", "COMX:"))
        self.baudLabel.setText(_translate("MainWindow", "BAUD"))
        self.comxTimeout.setText(_translate("MainWindow", "TIMEOUT"))
        self.bytesizeLabel.setText(_translate("MainWindow", "BYTESIZE"))
        self.prrityLabel.setText(_translate("MainWindow", "PARITY"))
        self.stopbitLabel.setText(_translate("MainWindow", "STOPBITS"))
        self.openBtn.setText(_translate("MainWindow", "OPEN"))
        self.closebtn.setText(_translate("MainWindow", "CLOSE"))
        self.checkBtn.setText(_translate("MainWindow", "CHECK"))
        self.aboutBtn.setText(_translate("MainWindow", "ABOUT"))
        self.statisticGroupLayout.setTitle(_translate("MainWindow", "Statistics"))
        self.sendedtext.setText(_translate("MainWindow", "已发送的爱心❤总数 -❤>"))
        self.debuggroupBox.setTitle(_translate("MainWindow", "Debug"))
        self.debugtextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">DEBUG HERE</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p></body></html>"))
        self.acceptedtext.setText(_translate("MainWindow", "已收到的爱心❤总数 -❤>"))
        self.acceptedGroupBox.setTitle(_translate("MainWindow", "接收❤区"))
        self.sendedGroupBox.setTitle(_translate("MainWindow", "发送❤区"))
        self.autoCheckBox.setText(_translate("MainWindow", "AUTO"))
        self.label_5.setText(_translate("MainWindow", "ms/次"))
        self.sendBtn.setText(_translate("MainWindow", "SEND"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "发射和接收爱心射线(づ￣3￣)づ╭❤～"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))

